default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("WEB_MAX_THREADS", 5) %>
  database: <%= ENV["DB_NAME"] || "spa_player_development" %>
  host: <%= ENV["DB_HOSTNAME"] || "localhost" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  username: <%= ENV["DB_USER"] || "" %>

development:
  <<: *default

test:
  <<: *default
  database: spa_player_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  host: <%= ENV["DB_HOSTNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["DB_USER"] %>
